#! /bin/bash
# Copyright Huawei Technologies Co., Ltd. 2022-2023. All rights reserved.
# 视频流云手机启动脚本配置文件，可配置云手机绑定的GPU、CPU、NUMA、编码卡、数据卷存放位置等
#
# 配置项生效方式标注说明：
#   [RESTART]  - 修改配置项后，通过 restart 命令重启云机即可生效
#   [RECREATE] - 修改配置项后，必须通过 delete + start 重新创建云机才能生效

# ----------------------------------------------
# 视频流云手机配置选项（可根据需要自行修改）
# ----------------------------------------------
# [RECREATE] 默认镜像名称，可根据需要自行修改
DOCKER_IMAGE=video:latest

# [RECREATE] 云手机运行内存大小，单位为 GB
RAM_SIZE_GB=6

# [RECREATE] 云手机存储大小，单位为 GB
STORAGE_SIZE_GB=16

# [RECREATE] 容器内 /system 分区的大小，单位为 MB。
# 默认为 0，表示不限制（走系统默认逻辑）。
# 若设置为非 0 值，系统会校验 /var/lib/docker 所在路径是否为 xfs 格式，若是 xfs 才生效。
SYSTEM_PARTITION_SIZE_MB=0

# [RECREATE] 使用NFS挂载启动的数据盘目录
NFS_DIR="/tmp/nfs"

# [RECREATE] 数据卷存放位置
USERDATA="/home/mount"

# 云手机屏幕宽、高、密度三者要匹配，720p(720 1280 320)，1080p(1080 1920 480)
# [RESTART] 云手机屏幕宽度
BUILD_WIDTH=720

# [RESTART] 云手机屏幕高度
BUILD_HEIGHT=1280

# [RESTART] 云手机屏幕密度
BUILD_DENSITY=320

# [RESTART] 云手机屏幕刷新帧率
BUILD_FPS=30

# [RECREATE] 云手机绑核方式 0：2容器2核(默认)；1：绑NUMA，每NUMA空前2个核
CPU_BIND_MODE=0

# [RECREATE] 选择编码卡（0:T432 1:Quadra 2:Va1e 3:open264）
ENCODECARD=1

# [RESTART] AMDGPU硬件配置下，T432/Quadra硬解使能开关, 1表示使能，其他值默认不使能
T432_QUADRA_DECODE_ENABLE=0

# [RECREATE] AMDGPU硬件配置下，C2解码器使能开关, 1表示使能，其他值默认不使能
ENABLE_AMD_C2_DECODE=0

# [RESTART] DC1000硬件配置下，硬解使能开关, 1表示使能，其他值默认不使能
ENABLE_HARD_DECODE=1

# [RECREATE] webrtc使能开关, 1表示使能，其他值默认不使能
ENABLE_WEBRTC_CONNECTION=0

# [RESTART] 渲染中间层开关，1表示使能，其他值默认不使能
ENABLE_RENDER_LAYER=0

# [RESTART] 是否使能f2fs文件系统格式，1表示使能(f2fs)，0表示不使能(ext4),其他值默认不使能
ENABLE_F2FS=0

# [RECREATE] 软渲染开关，1表示使能，其他值默认不使能
ENABLE_SOFT_RENDER=0

# [RECREATE] 是否使能纯64位，1表示使能，其他值默认不使能
ENABLE_ONLY64_KBOX=0

# [RECREATE] 是否启动时共享数据盘，0表示不共享，1表示共享
START_SHARE_DATA=0

USERDATA_MAP=(
    "${USERDATA}"
)

# 硬件绑定配置文件
source "$(dirname "${BASH_SOURCE[0]}")/hardware_bind.cfg"